import { Plus, Info } from 'lucide-react'
import { Button } from '@/components/ui/Button'

function Scope({ children, deny }: { children: React.ReactNode; deny?: boolean }) {
  return <span className={`rounded px-1.5 py-0.5 font-mono text-[10.5px] ${deny ? 'bg-status-danger/15 text-status-danger' : 'bg-status-success/15 text-status-success'}`}>{children}</span>
}

function KeyRow({ venue, name, fp, scopes }: { venue: string; name: string; fp: string; scopes: React.ReactNode }) {
  return (
    <div className="flex flex-wrap items-center gap-3.5 border-t border-border-default py-3.5 first:border-t-0">
      <div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-bg-surface-3 font-mono text-[11px] font-bold text-text-secondary">{venue}</div>
      <div className="min-w-0 flex-1">
        <div className="type-subhead font-semibold text-text-primary">{name}</div>
        <div className="font-mono type-caption text-text-tertiary">{fp}</div>
        <div className="mt-1.5 flex flex-wrap gap-1.5">{scopes}</div>
      </div>
    </div>
  )
}

export function KeysPage({ hasActiveKey, onAddKey }: { hasActiveKey: boolean; onAddKey: (label: string) => void }) {
  return (
    <div className="flex flex-col gap-5">
      <div className="flex flex-wrap items-center gap-2">
        <h1 className="type-title-l font-bold text-text-primary">Exchange API keys</h1>
        <span className={`rounded-full px-2.5 py-1 type-caption font-semibold ${hasActiveKey ? 'bg-status-success/15 text-status-success' : 'bg-bg-surface-2 text-text-tertiary'}`}>{hasActiveKey ? '1 active' : 'No trading key'}</span>
        <div className="ml-auto"><Button variant="secondary" size="sm" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={() => onAddKey('Deribit — main')}>Add key</Button></div>
      </div>
      <p className="type-subhead text-text-secondary">You create these keys on the venue and control them here. The software never holds withdrawal permission and cannot move funds.</p>
      <div className="rounded-2xl border border-border-default bg-bg-surface-1 p-5">
        {hasActiveKey && (
          <KeyRow venue="DBT" name="Deribit — main" fp="key ····9f2a1f9 · added just now" scopes={<><Scope>trade</Scope><Scope>read</Scope><Scope deny>no withdrawal</Scope></>} />
        )}
        <KeyRow venue="DBT" name="Deribit — read-only backup" fp="key ····3b70c4e · added 2026-06-01" scopes={<><Scope>read</Scope><Scope deny>no trade</Scope><Scope deny>no withdrawal</Scope></>} />
        <div className="mt-3.5 flex items-start gap-2 type-caption text-text-tertiary">
          <Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-text-faint" />
          Keys are generated by you on the venue and stored encrypted. Revoking a key here and on the venue immediately halts all execution.
        </div>
      </div>
    </div>
  )
}
